name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: unit-test
        run: bash ci/unit-test-app.sh
      - name: Build
        run: bash ci/build-app.sh
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .