name: java CI
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  unit-test:
    needs: checkout
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: . 
      - name: unit-test
        run: bash ci/unit-test-app.sh

  build:
    needs: checkout
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: . 
      - name: Build
        run: bash ci/build-app.sh
      