name: java CI
on: push


env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: upload repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  unit-test:
    needs: checkout
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: . 
      - name: unit-test
        run: bash ci/unit-test-app.sh

  build:
    needs: checkout
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: . 
      - name: Build
        run: bash ci/build-app.sh
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .
      
  docker-build:
    runs-on: ubuntu-latest
    needs: [build, unit-test]
    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build
        path: .
    - name: build docker
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/build-docker.sh
    - name: push docker
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/push-docker.sh

  Component-test:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build
        path: .
    - name: Execute component test
      run: bash ci/component-test.sh